export const items: string[] = [
    "Nick Gian",
    "Rakib Rsm",
    "Rakibul Islam",
    "Alice Johnson",
    // "Bob Smith",
    // "Eva Green",
    // "Michael Brown",
    // "Olivia Davis",
    // "David Wilson",
    // "Sophia Harris",
    // "Christopher Miller",
    // "Emma Martinez",
    // "Daniel Thompson",
    // "Ava Taylor",
    // "William Robinson",
    // "Mia Turner",
    // "Matthew White",
    // "Chloe Lewis", 
  ];